---
- name: Gather facts
  ansible.builtin.setup:

- name: Include distro-specific update tasks
  ansible.builtin.include_tasks: "{{ distro_task_map[ansible_facts['os_family']] }}"
  vars:
    distro_task_map:
      Debian: Debian.yml
      RedHat: RedHat.yml
      Suse: Suse.yml
  when: ansible_facts['os_family'] is defined and ansible_facts['os_family'] in distro_task_map
